version: '3'
services:
    frontend-nginx:
        container_name: frontend
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
        -   ./frontend:/var/www/frontend
        ports:
        -   "8080:80"
    
    api-nginx:
        container_name: api
        build:
            context: ./api/docker
            dockerfile: nginx.docker
        volumes:
            -  ./api:/var/www/api
        ports:
        -   "8081:80"
    
    api-php-fpm:
        container_name: php-api
        build:
            context: ./api/docker
            dockerfile: php-fpm.docker
        volumes:
        -   ./api:/var/www/api
        