version: '3'
services:
    frontend-nginx:
        container_name: frontend
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
        -   ./frontend:/var/www/frontend
        ports:
        -   "8080:80"